### ISSUE TITLE
Search Base selection input checking

### ISSUE THREAD

**Issue by velvet-valdes** [velvet-valdes/redLeg#6]
The search base selection automatically selects an OU even if none is entered.

**Comment by Bwilliamson55** [comment]
I believe it will select the last one in line.
This is due to the 
```
[int]$ans = Read-Host `n 'Enter selection'
$searchbase += $OUhash[$ans-1]
```
Not having a catch for zero or null. Zero or null will end up being $ans-1, or, the last index in the hash table. 
Which, by the way, is a handy way to select the last entry in an array or hash- "-1".

I'll build a catch into that part on my next commit.

**Comment by velvet-valdes** [comment]
Was able to get that taken care of with the last commit.  Added some input checking
